displayName: celguard
runtime: wasm
type: middleware

summary: "Easy request filtering for Traefik using Common Expression Language (CEL) configuration (celguard)"

testData:
  config:
    matcher:
      rules:
        - name: useragent
          tests:
            - request.headers.contains('user-agent') == false
