displayName: celguard
runtime: wasm
type: middleware

summary: "Easy request filtering for Traefik using Common Expression Language (CEL) configuration (celguard)"

testData:
  config:
    actions:
      - &block_empty_useragent
        response: { status: 400 }
    rules:
      - name: useragent
        log: warn
        tests:
          - request.header.contains('user-agent') == false
        action: *block_empty_useragent
