[package]
name = "celguard"
version = "0.1.2"
edition = "2024"

[dependencies]
http-wasm-guest = "0.10"
serde = { version = "1.0", default-features = false, features = ["derive"]}
serde-saphyr = "0.0.23"
log = "0.4"
cel = "0.13"
anyhow = "1.0"

[dev-dependencies]
test-log = "0.2"
testresult = "0.4.1"
