[package]
name = "celguard"
version = "0.2.1"
edition = "2024"
rust-version = "1.89.0"

[dependencies]
http-wasm-guest = "1.0"
#http-wasm-guest = { path = "../http-wasm-guest" }
serde = { version = "1.0", default-features = false, features = ["derive"]}
serde-saphyr =  { version = "1", default-features = false, features = ["deserialize"] }
cel = "0.14"
anyhow = "1.0"
log = "0.4"

[dev-dependencies]
test-log = "0.2"
testresult = "0.4"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
panic = "deny"
unwrap_used = "deny"
missing_assert_message = "warn"
map_unwrap_or = "warn"
get_unwrap = "warn"
unwrap_in_result = "warn"
string_slice = "warn"
