# minimal example for a rule which matches on all requests and references an action without a response.
# This will not modify the response in any way and continues with the processing.
actions:
  - &allow
    continue: true
rules:
  - name: example1
    action: *allow
