rules:
  - name: useragent
    log: warn
    tests:
      - request.header.contains('user-agent') == false
      - request.header['user-agent'].matches('(?i)python-requests|libwww-perl')
    action: block

  - name: method
    tests:
      - request.method != 'GET'
    action: block

actions:
  block:
    response: { status: 400 }
