
plugin:
  default_status: 400

matcher:
  source_ip: request.headers['x-real-ip'].get_first()

  actions:
    - &default_action
      response: { status: 400 }

  rules:
    - name: method
      log: warn
      tests:
        - request.method in ['GET','HEAD','OPTIONS'] != true
      action:
        response: { status: 405, header: { allow: "GET, HEAD, OPTIONS" } }

    - name: empty_agent
      log: warn
      tests:
        - request.headers.contains('user-agent') == false
        - request.headers['user-agent'].all(h, h.trim() == '')

    - name: whitelist
      tests:
        - request.path == '/'
        - request.path == '/status'
        - request.path == '/robots.txt'
        - request.path == '/sitemap.xml'
        - request.path.startsWith('/js/')
        - request.path.startsWith('/css/')
        - request.path.startsWith('/images/')
      action:
        continue: true

    - name: default
      log: warn
      action: *default_action
