plugin:
  default_status: 400 # used for action responses without status
  default_action:
    log: warn
    response: { status: 400 }

matcher:
  source_ip: request.headers['x-real-ip']

  rules:
    - name: method
      tests:
        - request.method in ['GET','HEAD','OPTIONS'] != true
      action:
        response: { status: 405, header: { allow: "GET, HEAD, OPTIONS" } }
        log: warn

    - name: empty_agent
      tests:
        - request.headers.contains('user-agent') == false
        - request.headers['user-agent'].trim() == ''
      action:
        log: warn
        response: { status: 401, body: "empty agent" }

    - name: path
      tests:
        - request.path.matches('/\\.')

    - name: whitelist
      tests:
        - request.path == '/'
        - request.path == '/status'
        - request.path == '/robots.txt'
        - request.path == '/sitemap.xml'
        - request.path.startsWith('/js/')
        - request.path.startsWith('/css/')
        - request.path.startsWith('/images/')
      action:
        log: info
        continue: true

    - name: default
