source_ip: request.header['x-real-ip'].get_first()

actions:
  - &allow
    continue: true
  - &bad_request
    response: { status: 400 }
  - &method_not_allowed
    response: { status: 405, header: { allow: "GET, HEAD, OPTIONS" } }

rules:
  - name: method
    log: warn
    tests:
      - request.method in ['GET','HEAD','OPTIONS'] != true
    action: *method_not_allowed

  - name: empty_agent
    log: warn
    tests:
      - request.header.contains('user-agent') == false
      - request.header['user-agent'].all(h, h.trim() == '')
    action: *bad_request

  - name: whitelist
    tests:
      - request.path == '/'
      - request.path == '/status'
      - request.path == '/robots.txt'
      - request.path == '/sitemap.xml'
      - request.path.startsWith('/js/')
      - request.path.startsWith('/css/')
      - request.path.startsWith('/images/')
    action: *allow

  - name: default
    log: warn
